# Generated by Django 6.1 on 2026-08-15 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_vaultitem_host_vaultgroup_vaultitem_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ('-created_at',), 'verbose_name': 'Evento de auditoria', 'verbose_name_plural': 'Eventos de auditoria'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Cadastro de usuário', 'verbose_name_plural': 'Cadastros de usuários'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organização', 'verbose_name_plural': 'Organizações'},
        ),
        migrations.AlterModelOptions(
            name='vaultgroup',
            options={'ordering': ('name',), 'verbose_name': 'Grupo de senhas', 'verbose_name_plural': 'Grupos de senhas'},
        ),
        migrations.AlterModelOptions(
            name='vaultitem',
            options={'ordering': ('title',), 'verbose_name': 'Senha do cofre', 'verbose_name_plural': 'Senhas do cofre'},
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Excluiu'), ('reveal', 'Revelou'), ('copy', 'Copiou')], max_length=10, verbose_name='ação'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário responsável'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='realizado em'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='item_title',
            field=models.CharField(max_length=150, verbose_name='título da senha'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='gerenciador.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='vault_item_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='identificador da senha'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aprovado e ativo'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gerenciador.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('member', 'Membro')], default='member', max_length=10, verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criada em'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='identificador curto'),
        ),
        migrations.AlterField(
            model_name='vaultgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='vaultgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_groups', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='vaultgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='vaultgroup',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='vaultgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_groups', to='gerenciador.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criada em'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_items', to=settings.AUTH_USER_MODEL, verbose_name='criada por'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_items', to='gerenciador.vaultgroup', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='host',
            field=models.CharField(blank=True, max_length=255, verbose_name='IP ou nome do equipamento'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='compartilhada'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='notes_encrypted',
            field=models.BinaryField(blank=True, default=b'', verbose_name='observações criptografadas'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to='gerenciador.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='secret_encrypted',
            field=models.BinaryField(verbose_name='senha criptografada'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='title',
            field=models.CharField(max_length=150, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizada em'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='username',
            field=models.CharField(blank=True, max_length=254, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='website',
            field=models.URLField(blank=True, verbose_name='site'),
        ),
    ]
