# Generated by Django 6.1 on 2026-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_alter_auditevent_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Excluiu'), ('reveal', 'Revelou'), ('copy', 'Copiou'), ('user_approve', 'Aprovou usuário'), ('user_suspend', 'Suspendeu usuário'), ('group_update', 'Renomeou grupo')], max_length=20, verbose_name='ação'),
        ),
    ]
