# Generated by Django 6.1 on 2026-08-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Excluiu'), ('reveal', 'Revelou'), ('copy', 'Copiou'), ('user_approve', 'Aprovou usuário'), ('user_suspend', 'Suspendeu usuário'), ('user_role', 'Alterou perfil de usuário'), ('user_logout', 'Encerrou sessões de usuário'), ('user_unlock', 'Desbloqueou acesso de usuário'), ('group_update', 'Renomeou grupo'), ('group_delete', 'Excluiu grupo')], max_length=20, verbose_name='ação'),
        ),
    ]
