# Generated by Django 6.1 on 2026-08-15 16:32

from django.conf import settings
from django.db import migrations, models


# Preserva o compartilhamento existente durante a alteração.
def migrate_sharing(apps, schema_editor):
    vault_item = apps.get_model('gerenciador', 'VaultItem')
    vault_item.objects.filter(is_shared=True).update(visibility='organization')


def reverse_sharing(apps, schema_editor):
    vault_item = apps.get_model('gerenciador', 'VaultItem')
    vault_item.objects.exclude(visibility='private').update(is_shared=True)


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0006_alter_auditevent_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vaultitem',
            name='gerenciador_organiz_0e473b_idx',
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_vault_items', to=settings.AUTH_USER_MODEL, verbose_name='compartilhada com'),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='visibility',
            field=models.CharField(choices=[('private', 'Somente eu'), ('specific', 'Usuários específicos'), ('organization', 'Todos da Carmel')], default='private', max_length=12, verbose_name='visibilidade'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Excluiu'), ('reveal', 'Revelou'), ('copy', 'Copiou'), ('share_update', 'Alterou compartilhamento'), ('user_approve', 'Aprovou usuário'), ('user_suspend', 'Suspendeu usuário'), ('user_role', 'Alterou perfil de usuário'), ('user_logout', 'Encerrou sessões de usuário'), ('user_unlock', 'Desbloqueou acesso de usuário'), ('group_update', 'Renomeou grupo'), ('group_delete', 'Excluiu grupo')], max_length=20, verbose_name='ação'),
        ),
        migrations.AddIndex(
            model_name='vaultitem',
            index=models.Index(fields=['organization', 'visibility'], name='gerenciador_organiz_76eb5d_idx'),
        ),
        migrations.RunPython(migrate_sharing, reverse_sharing),
        migrations.RemoveField(
            model_name='vaultitem',
            name='is_shared',
        ),
    ]
