# Generated by Django 6.1 on 2026-08-16 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0007_remove_vaultitem_gerenciador_organiz_0e473b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário responsável'),
        ),
        migrations.AlterField(
            model_name='vaultgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_groups', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_items', to=settings.AUTH_USER_MODEL, verbose_name='criada por'),
        ),
    ]
